################################################################################
# ElastiCache Redis 7 (spec §4.6)
#
# Launch-lite: cache.t4g.micro single-node. Multi-AZ replication arrives via
# var.redis_num_cache_clusters > 1 (upgrade lever).
#
# Auth token + TLS in transit are both ON. The application reads the auth
# token via ECS task `secrets[]` injection from /slpa/${env}/redis/auth-token.
################################################################################

resource "aws_elasticache_subnet_group" "main" {
  name       = "slpa-${var.environment}-redis"
  subnet_ids = var.private_subnet_ids

  tags = {
    Name = "slpa-${var.environment}-redis-subnet-group"
  }
}

# Redis auth token — Redis is strict about charset (only printable ASCII excl.
# space + a few specials). Spring's Lettuce client is happy with the default
# charset minus problematic JDBC-ish characters. 32 chars is well above the
# 16-char minimum.
resource "random_password" "redis_auth" {
  length           = 32
  special          = true
  override_special = "!&#$^<>-"
}

resource "aws_ssm_parameter" "redis_auth_token" {
  name        = "/slpa/${var.environment}/redis/auth-token"
  description = "ElastiCache Redis AUTH token. Generated by Terraform; rotate via tainting random_password.redis_auth."
  type        = "SecureString"
  value       = random_password.redis_auth.result

  tags = {
    Name = "slpa-${var.environment}-redis-auth"
  }

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_elasticache_replication_group" "main" {
  replication_group_id = "slpa-${var.environment}-redis"
  description          = "SLPA ${var.environment} Redis - sessions, bid rate-limit counters, auction countdown timers, bot heartbeat state."

  engine         = "redis"
  engine_version = "7.1"

  node_type = var.redis_node_type
  port      = 6379

  # num_cache_clusters > 1 enables Multi-AZ + automatic_failover.
  # At launch-lite (= 1) both flags must be off.
  num_cache_clusters         = var.redis_num_cache_clusters
  automatic_failover_enabled = var.redis_num_cache_clusters > 1
  multi_az_enabled           = var.redis_num_cache_clusters > 1

  subnet_group_name  = aws_elasticache_subnet_group.main.name
  security_group_ids = [var.redis_security_group_id]

  at_rest_encryption_enabled = true
  transit_encryption_enabled = true
  auth_token                 = random_password.redis_auth.result

  # transit_encryption_mode required when transit_encryption_enabled = true.
  # 'required' rejects plaintext connections; 'preferred' allows fallback
  # (avoid in prod).
  transit_encryption_mode = "required"

  snapshot_retention_limit = 5
  snapshot_window          = "03:00-04:00" # UTC
  maintenance_window       = "sun:05:00-sun:06:00"

  apply_immediately = false

  tags = {
    Name = "slpa-${var.environment}-redis"
  }
}
