################################################################################
# RDS Postgres 17 (spec §4.5)
#
# Launch-lite: db.t4g.micro single-AZ + 20 GB gp3 + 7d PITR. Master credentials
# generated by Terraform (random_password) and stored as SecureString in
# Parameter Store. Application reads via ECS task `secrets[]` injection.
#
# Connection URL is NOT pre-built here — the application's ECS task definition
# (compute module) constructs it from the writer endpoint output + the SSM
# parameter values, so a future RDS endpoint change (e.g. failover, instance
# class change) doesn't require regenerating any secret.
################################################################################

# ----- Subnet group --------------------------------------------------------- #

resource "aws_db_subnet_group" "main" {
  name       = "slpa-${var.environment}-rds"
  subnet_ids = var.private_subnet_ids

  tags = {
    Name = "slpa-${var.environment}-rds-subnet-group"
  }
}

# ----- Master credentials --------------------------------------------------- #

# RDS Postgres password — generated, stored in Parameter Store. Length 32 with
# Postgres-safe special chars only (avoids @ which is reserved for JDBC URL
# parsing in some drivers, and avoids quote/slash/backslash which break
# shell-friendly env-var injection).
resource "random_password" "rds_master" {
  length           = 32
  special          = true
  override_special = "!#$%&*+,-.<=>?_~"

  # Regenerate the password if the keepers change. Empty keepers = stable.
  keepers = {}
}

resource "aws_ssm_parameter" "rds_master_password" {
  name        = "/slpa/${var.environment}/rds/password"
  description = "RDS Postgres master password. Auto-generated by Terraform; rotate via tainting random_password.rds_master."
  type        = "SecureString"
  value       = random_password.rds_master.result

  tags = {
    Name = "slpa-${var.environment}-rds-password"
  }

  # Don't rotate Parameter Store value on every plan if the random_password
  # value drifts (it shouldn't, but lifecycle.ignore_changes provides a
  # safety net).
  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "rds_master_username" {
  name        = "/slpa/${var.environment}/rds/username"
  description = "RDS Postgres master username."
  type        = "String"
  value       = "slpa"

  tags = {
    Name = "slpa-${var.environment}-rds-username"
  }
}

# ----- The instance --------------------------------------------------------- #

resource "aws_db_instance" "main" {
  identifier = "slpa-${var.environment}-postgres"

  engine                      = "postgres"
  engine_version              = "17.5"
  allow_major_version_upgrade = false
  auto_minor_version_upgrade  = true

  instance_class = var.rds_instance_class

  allocated_storage     = var.rds_allocated_storage
  max_allocated_storage = 100 # autoscaling ceiling — bump in tfvars when traffic justifies more
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = "slpa"
  username = "slpa"
  password = random_password.rds_master.result
  port     = 5432

  vpc_security_group_ids = [var.rds_security_group_id]
  db_subnet_group_name   = aws_db_subnet_group.main.name
  publicly_accessible    = false

  multi_az = var.rds_multi_az

  backup_retention_period = 7
  backup_window           = "04:00-05:00" # UTC
  maintenance_window      = "Sun:06:00-Sun:07:00"

  performance_insights_enabled          = var.rds_database_insights_enabled
  performance_insights_retention_period = var.rds_database_insights_enabled ? var.rds_pi_retention_days : null

  enabled_cloudwatch_logs_exports = ["postgresql"]

  deletion_protection       = true
  skip_final_snapshot       = false
  final_snapshot_identifier = "slpa-${var.environment}-postgres-final-${formatdate("YYYYMMDD-hhmmss", timestamp())}"
  copy_tags_to_snapshot     = true

  apply_immediately = false # changes apply during the maintenance window

  tags = {
    Name = "slpa-${var.environment}-postgres"
  }

  lifecycle {
    # final_snapshot_identifier embeds a timestamp() that ticks every plan;
    # ignore_changes prevents diff-on-every-plan churn.
    ignore_changes = [final_snapshot_identifier]
  }
}
