--
-- PostgreSQL database dump
--


-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_actions (
    id bigint NOT NULL,
    action_type character varying(40) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    details jsonb,
    notes text,
    target_id bigint NOT NULL,
    target_type character varying(20) NOT NULL,
    admin_user_id bigint NOT NULL,
    CONSTRAINT admin_actions_action_type_check CHECK (((action_type)::text = ANY ((ARRAY['DISMISS_REPORT'::character varying, 'WARN_SELLER_FROM_REPORT'::character varying, 'SUSPEND_LISTING_FROM_REPORT'::character varying, 'CANCEL_LISTING_FROM_REPORT'::character varying, 'CREATE_BAN'::character varying, 'LIFT_BAN'::character varying, 'PROMOTE_USER'::character varying, 'DEMOTE_USER'::character varying, 'RESET_FRIVOLOUS_COUNTER'::character varying, 'REINSTATE_LISTING'::character varying, 'DISPUTE_RESOLVED'::character varying, 'LISTING_CANCELLED_VIA_DISPUTE'::character varying, 'WITHDRAWAL_REQUESTED'::character varying, 'OWNERSHIP_RECHECK_INVOKED'::character varying, 'TERMINAL_SECRET_ROTATED'::character varying, 'USER_DELETED_BY_ADMIN'::character varying])::text[]))),
    CONSTRAINT admin_actions_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['USER'::character varying, 'LISTING'::character varying, 'REPORT'::character varying, 'FRAUD_FLAG'::character varying, 'BAN'::character varying, 'DISPUTE'::character varying, 'WITHDRAWAL'::character varying, 'TERMINAL_SECRET'::character varying, 'AUCTION'::character varying])::text[])))
);


--
-- Name: admin_actions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_actions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auction_photos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auction_photos (
    id bigint NOT NULL,
    content_type character varying(50) NOT NULL,
    object_key character varying(500) NOT NULL,
    size_bytes bigint NOT NULL,
    sort_order integer NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    auction_id bigint NOT NULL
);


--
-- Name: auction_photos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auction_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auction_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auction_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auction_tags (
    auction_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: auctions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auctions (
    id bigint NOT NULL,
    agent_fee_amt bigint,
    agent_fee_rate numeric(5,4),
    assigned_bot_uuid uuid,
    bid_count integer NOT NULL,
    bot_check_failures integer NOT NULL,
    buy_now_price bigint,
    commission_amt bigint,
    commission_rate numeric(5,4),
    consecutive_world_api_failures integer DEFAULT 0 NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    current_bid bigint NOT NULL,
    current_bidder_id bigint,
    duration_hours integer NOT NULL,
    end_outcome character varying(32),
    ended_at timestamp(6) with time zone,
    ends_at timestamp(6) with time zone,
    final_bid_amount bigint,
    last_bot_check_at timestamp(6) with time zone,
    last_ownership_check_at timestamp(6) with time zone,
    listing_fee_amt bigint,
    listing_fee_paid boolean NOT NULL,
    listing_fee_paid_at timestamp(6) with time zone,
    listing_fee_txn character varying(255),
    original_ends_at timestamp(6) with time zone,
    post_cancel_watch_until timestamp(6) with time zone,
    realty_group_id bigint,
    reserve_price bigint,
    sale_sentinel_price bigint,
    seller_desc text,
    snipe_protect boolean NOT NULL,
    snipe_window_min integer,
    starting_bid bigint NOT NULL,
    starts_at timestamp(6) with time zone,
    status character varying(30) NOT NULL,
    suspended_at timestamp(6) with time zone,
    title character varying(120) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    verification_method character varying(20),
    verification_notes text,
    verification_tier character varying(10),
    verified_at timestamp(6) with time zone,
    winner_id bigint,
    winner_user_id bigint,
    listing_agent_id bigint,
    parcel_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    CONSTRAINT auctions_end_outcome_check CHECK (((end_outcome)::text = ANY ((ARRAY['SOLD'::character varying, 'RESERVE_NOT_MET'::character varying, 'NO_BIDS'::character varying, 'BOUGHT_NOW'::character varying])::text[]))),
    CONSTRAINT auctions_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'DRAFT_PAID'::character varying, 'VERIFICATION_PENDING'::character varying, 'VERIFICATION_FAILED'::character varying, 'ACTIVE'::character varying, 'ENDED'::character varying, 'ESCROW_PENDING'::character varying, 'ESCROW_FUNDED'::character varying, 'TRANSFER_PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying, 'DISPUTED'::character varying, 'SUSPENDED'::character varying])::text[]))),
    CONSTRAINT auctions_verification_method_check CHECK (((verification_method)::text = ANY ((ARRAY['UUID_ENTRY'::character varying, 'REZZABLE'::character varying, 'SALE_TO_BOT'::character varying])::text[]))),
    CONSTRAINT auctions_verification_tier_check CHECK (((verification_tier)::text = ANY ((ARRAY['SCRIPT'::character varying, 'BOT'::character varying, 'HUMAN'::character varying])::text[])))
);


--
-- Name: auctions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auctions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auctions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bans (
    id bigint NOT NULL,
    ban_type character varying(10) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone,
    ip_address character varying(45),
    lifted_at timestamp(6) with time zone,
    lifted_reason text,
    notes text,
    reason_category character varying(20) NOT NULL,
    sl_avatar_uuid uuid,
    admin_user_id bigint NOT NULL,
    lifted_by_user_id bigint,
    CONSTRAINT bans_ban_type_check CHECK (((ban_type)::text = ANY ((ARRAY['IP'::character varying, 'AVATAR'::character varying, 'BOTH'::character varying])::text[]))),
    CONSTRAINT bans_reason_category_check CHECK (((reason_category)::text = ANY ((ARRAY['SHILL_BIDDING'::character varying, 'FRAUDULENT_SELLER'::character varying, 'TOS_ABUSE'::character varying, 'SPAM'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: bans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bids; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bids (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    bid_type character varying(16) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    ip_address character varying(45),
    new_ends_at timestamp(6) with time zone,
    proxy_bid_id bigint,
    snipe_extension_minutes integer,
    auction_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT bids_bid_type_check CHECK (((bid_type)::text = ANY ((ARRAY['MANUAL'::character varying, 'PROXY_AUTO'::character varying, 'BUY_NOW'::character varying])::text[])))
);


--
-- Name: bids_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bids ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bot_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bot_tasks (
    id bigint NOT NULL,
    assigned_bot_uuid uuid,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    expected_auth_buyer_uuid uuid,
    expected_max_sale_price_lindens bigint,
    expected_owner_uuid uuid,
    expected_sale_price_lindens bigint,
    expected_seller_uuid uuid,
    expected_winner_uuid uuid,
    failure_reason character varying(500),
    last_check_at timestamp(6) with time zone,
    last_updated_at timestamp(6) with time zone NOT NULL,
    next_run_at timestamp(6) with time zone,
    parcel_uuid uuid NOT NULL,
    position_x double precision,
    position_y double precision,
    position_z double precision,
    recurrence_interval_seconds integer,
    region_name character varying(100),
    result_data jsonb,
    sentinel_price bigint NOT NULL,
    status character varying(20) NOT NULL,
    task_type character varying(20) NOT NULL,
    auction_id bigint NOT NULL,
    escrow_id bigint,
    CONSTRAINT bot_tasks_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT bot_tasks_task_type_check CHECK (((task_type)::text = ANY ((ARRAY['VERIFY'::character varying, 'MONITOR_AUCTION'::character varying, 'MONITOR_ESCROW'::character varying])::text[])))
);


--
-- Name: bot_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bot_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bot_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bot_workers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bot_workers (
    id bigint NOT NULL,
    first_seen_at timestamp(6) with time zone NOT NULL,
    last_seen_at timestamp(6) with time zone NOT NULL,
    name character varying(80) NOT NULL,
    sl_uuid character varying(36) NOT NULL
);


--
-- Name: bot_workers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bot_workers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bot_workers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cancellation_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cancellation_logs (
    id bigint NOT NULL,
    cancelled_at timestamp(6) with time zone NOT NULL,
    cancelled_by_admin_id bigint,
    cancelled_from_status character varying(30) NOT NULL,
    had_bids boolean NOT NULL,
    penalty_amount_l bigint,
    penalty_kind character varying(30),
    reason character varying(500),
    auction_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    CONSTRAINT cancellation_logs_penalty_kind_check CHECK (((penalty_kind)::text = ANY ((ARRAY['NONE'::character varying, 'WARNING'::character varying, 'PENALTY'::character varying, 'PENALTY_AND_30D'::character varying, 'PERMANENT_BAN'::character varying])::text[])))
);


--
-- Name: cancellation_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cancellation_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cancellation_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: escrow_transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.escrow_transactions (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    error_message character varying(500),
    sl_transaction_id character varying(100),
    status character varying(20) NOT NULL,
    terminal_id character varying(100),
    type character varying(40) NOT NULL,
    auction_id bigint,
    escrow_id bigint,
    payee_id bigint,
    payer_id bigint,
    CONSTRAINT escrow_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT escrow_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['AUCTION_ESCROW_PAYMENT'::character varying, 'AUCTION_ESCROW_PAYOUT'::character varying, 'AUCTION_ESCROW_REFUND'::character varying, 'AUCTION_ESCROW_COMMISSION'::character varying, 'LISTING_FEE_PAYMENT'::character varying, 'LISTING_FEE_REFUND'::character varying, 'LISTING_PENALTY_PAYMENT'::character varying])::text[])))
);


--
-- Name: escrow_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.escrow_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.escrow_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: escrows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.escrows (
    id bigint NOT NULL,
    commission_amt bigint NOT NULL,
    completed_at timestamp(6) with time zone,
    consecutive_world_api_failures integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    dispute_description text,
    dispute_reason_category character varying(40),
    disputed_at timestamp(6) with time zone,
    expired_at timestamp(6) with time zone,
    final_bid_amount bigint NOT NULL,
    freeze_reason character varying(40),
    frozen_at timestamp(6) with time zone,
    funded_at timestamp(6) with time zone,
    last_checked_at timestamp(6) with time zone,
    payment_deadline timestamp(6) with time zone NOT NULL,
    payout_amt bigint NOT NULL,
    reminder_sent_at timestamp(6) with time zone,
    review_required boolean NOT NULL,
    seller_evidence_images jsonb,
    seller_evidence_submitted_at timestamp(6) with time zone,
    seller_evidence_text character varying(2000),
    sl_transaction_key character varying(64),
    state character varying(30) NOT NULL,
    transfer_confirmed_at timestamp(6) with time zone,
    transfer_deadline timestamp(6) with time zone,
    winner_evidence_images jsonb,
    auction_id bigint NOT NULL,
    CONSTRAINT escrows_state_check CHECK (((state)::text = ANY ((ARRAY['ESCROW_PENDING'::character varying, 'FUNDED'::character varying, 'TRANSFER_PENDING'::character varying, 'COMPLETED'::character varying, 'DISPUTED'::character varying, 'EXPIRED'::character varying, 'FROZEN'::character varying])::text[])))
);


--
-- Name: escrows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.escrows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.escrows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fraud_flags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fraud_flags (
    id bigint NOT NULL,
    admin_notes text,
    created_at timestamp(6) with time zone NOT NULL,
    detected_at timestamp(6) with time zone NOT NULL,
    evidence_json jsonb,
    reason character varying(40) NOT NULL,
    resolved boolean NOT NULL,
    resolved_at timestamp(6) with time zone,
    auction_id bigint,
    parcel_id bigint NOT NULL,
    resolved_by_user_id bigint,
    CONSTRAINT fraud_flags_reason_check CHECK (((reason)::text = ANY ((ARRAY['OWNERSHIP_CHANGED_TO_UNKNOWN'::character varying, 'PARCEL_DELETED_OR_MERGED'::character varying, 'WORLD_API_FAILURE_THRESHOLD'::character varying, 'ESCROW_WRONG_PAYER'::character varying, 'ESCROW_UNKNOWN_OWNER'::character varying, 'ESCROW_PARCEL_DELETED'::character varying, 'ESCROW_WORLD_API_FAILURE'::character varying, 'BOT_AUTH_BUYER_REVOKED'::character varying, 'BOT_PRICE_DRIFT'::character varying, 'BOT_OWNERSHIP_CHANGED'::character varying, 'BOT_ACCESS_REVOKED'::character varying, 'CANCEL_AND_SELL'::character varying])::text[])))
);


--
-- Name: fraud_flags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fraud_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fraud_flags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: listing_fee_refunds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.listing_fee_refunds (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_queued_at timestamp(6) with time zone,
    processed_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    terminal_command_id bigint,
    txn_ref character varying(255),
    auction_id bigint NOT NULL,
    CONSTRAINT listing_fee_refunds_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: listing_fee_refunds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.listing_fee_refunds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.listing_fee_refunds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: listing_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.listing_reports (
    id bigint NOT NULL,
    admin_notes text,
    created_at timestamp(6) with time zone NOT NULL,
    details text NOT NULL,
    reason character varying(30) NOT NULL,
    reviewed_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    subject character varying(100) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    auction_id bigint NOT NULL,
    reporter_id bigint NOT NULL,
    reviewed_by bigint,
    CONSTRAINT listing_reports_reason_check CHECK (((reason)::text = ANY ((ARRAY['INACCURATE_DESCRIPTION'::character varying, 'WRONG_TAGS'::character varying, 'SHILL_BIDDING'::character varying, 'FRAUDULENT_SELLER'::character varying, 'DUPLICATE_LISTING'::character varying, 'NOT_ACTUALLY_FOR_SALE'::character varying, 'TOS_VIOLATION'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT listing_reports_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'REVIEWED'::character varying, 'DISMISSED'::character varying, 'ACTION_TAKEN'::character varying])::text[])))
);


--
-- Name: listing_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.listing_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.listing_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    body character varying(500) NOT NULL,
    category character varying(64) NOT NULL,
    coalesce_key character varying(160),
    created_at timestamp(6) with time zone NOT NULL,
    data jsonb,
    read boolean DEFAULT false NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notification_category_check CHECK (((category)::text = ANY ((ARRAY['OUTBID'::character varying, 'PROXY_EXHAUSTED'::character varying, 'AUCTION_WON'::character varying, 'AUCTION_LOST'::character varying, 'AUCTION_ENDED_SOLD'::character varying, 'AUCTION_ENDED_RESERVE_NOT_MET'::character varying, 'AUCTION_ENDED_NO_BIDS'::character varying, 'AUCTION_ENDED_BOUGHT_NOW'::character varying, 'ESCROW_FUNDED'::character varying, 'ESCROW_TRANSFER_CONFIRMED'::character varying, 'ESCROW_PAYOUT'::character varying, 'ESCROW_EXPIRED'::character varying, 'ESCROW_DISPUTED'::character varying, 'ESCROW_FROZEN'::character varying, 'ESCROW_PAYOUT_STALLED'::character varying, 'ESCROW_TRANSFER_REMINDER'::character varying, 'LISTING_VERIFIED'::character varying, 'LISTING_SUSPENDED'::character varying, 'LISTING_REINSTATED'::character varying, 'LISTING_REVIEW_REQUIRED'::character varying, 'LISTING_CANCELLED_BY_SELLER'::character varying, 'LISTING_REMOVED_BY_ADMIN'::character varying, 'LISTING_WARNED'::character varying, 'REVIEW_RECEIVED'::character varying, 'REVIEW_RESPONSE_WINDOW_CLOSING'::character varying, 'SYSTEM_ANNOUNCEMENT'::character varying, 'DISPUTE_FILED_AGAINST_SELLER'::character varying, 'DISPUTE_RESOLVED'::character varying, 'RECONCILIATION_MISMATCH'::character varying, 'WITHDRAWAL_COMPLETED'::character varying, 'WITHDRAWAL_FAILED'::character varying])::text[])))
);


--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parcel_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parcel_tags (
    id bigint NOT NULL,
    active boolean NOT NULL,
    category character varying(50) NOT NULL,
    code character varying(50) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description text,
    label character varying(100) NOT NULL,
    sort_order integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: parcel_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parcel_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parcel_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parcels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parcels (
    id bigint NOT NULL,
    area_sqm integer,
    continent_name character varying(50),
    created_at timestamp(6) with time zone NOT NULL,
    description text,
    grid_x double precision,
    grid_y double precision,
    last_checked timestamp(6) with time zone,
    layout_map_at timestamp(6) with time zone,
    layout_map_data jsonb,
    layout_map_url text,
    location character varying(100),
    maturity_rating character varying(10),
    owner_type character varying(10),
    owner_uuid uuid,
    position_x double precision,
    position_y double precision,
    position_z double precision,
    region_name character varying(100),
    sl_parcel_uuid uuid NOT NULL,
    slurl text,
    snapshot_url text,
    verified boolean NOT NULL,
    verified_at timestamp(6) with time zone
);


--
-- Name: parcels_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parcels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parcels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proxy_bids; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proxy_bids (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    max_amount bigint NOT NULL,
    status character varying(16) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    auction_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT proxy_bids_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'EXHAUSTED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: proxy_bids_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proxy_bids ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proxy_bids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reconciliation_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reconciliation_runs (
    id bigint NOT NULL,
    drift bigint,
    error_message character varying(500),
    expected_locked_sum bigint NOT NULL,
    observed_balance bigint,
    ran_at timestamp(6) with time zone NOT NULL,
    status character varying(16) NOT NULL,
    CONSTRAINT reconciliation_runs_status_check CHECK (((status)::text = ANY ((ARRAY['BALANCED'::character varying, 'MISMATCH'::character varying, 'ERROR'::character varying])::text[])))
);


--
-- Name: reconciliation_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reconciliation_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reconciliation_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    ip_address character varying(45),
    last_used_at timestamp(6) with time zone,
    revoked_at timestamp(6) with time zone,
    token_hash character varying(64) NOT NULL,
    user_agent character varying(512),
    user_id bigint NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_flags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_flags (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    elaboration character varying(500),
    reason character varying(20) NOT NULL,
    flagger_id bigint NOT NULL,
    review_id bigint NOT NULL,
    CONSTRAINT review_flags_reason_check CHECK (((reason)::text = ANY ((ARRAY['SPAM'::character varying, 'ABUSIVE'::character varying, 'OFF_TOPIC'::character varying, 'FALSE_INFO'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: review_flags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_flags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_responses (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    text character varying(500) NOT NULL,
    review_id bigint NOT NULL
);


--
-- Name: review_responses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review_responses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_responses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    flag_count integer NOT NULL,
    rating integer NOT NULL,
    response_closing_reminder_sent_at timestamp(6) with time zone,
    revealed_at timestamp(6) with time zone,
    reviewed_role character varying(10) NOT NULL,
    submitted_at timestamp(6) with time zone NOT NULL,
    text character varying(500),
    visible boolean NOT NULL,
    auction_id bigint NOT NULL,
    reviewee_id bigint NOT NULL,
    reviewer_id bigint NOT NULL,
    CONSTRAINT reviews_reviewed_role_check CHECK (((reviewed_role)::text = ANY ((ARRAY['SELLER'::character varying, 'BUYER'::character varying])::text[])))
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_auctions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_auctions (
    id bigint NOT NULL,
    saved_at timestamp(6) with time zone NOT NULL,
    auction_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: saved_auctions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saved_auctions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_auctions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sl_im_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sl_im_message (
    id bigint NOT NULL,
    attempts integer NOT NULL,
    avatar_uuid character varying(36) NOT NULL,
    coalesce_key character varying(128),
    created_at timestamp(6) with time zone NOT NULL,
    delivered_at timestamp(6) with time zone,
    message_text character varying(1024) NOT NULL,
    status character varying(16) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT sl_im_message_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'DELIVERED'::character varying, 'EXPIRED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: sl_im_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sl_im_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sl_im_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terminal_commands; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terminal_commands (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    amount bigint NOT NULL,
    attempt_count integer NOT NULL,
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    dispatched_at timestamp(6) with time zone,
    escrow_id bigint,
    idempotency_key character varying(80) NOT NULL,
    last_error character varying(500),
    listing_fee_refund_id bigint,
    next_attempt_at timestamp(6) with time zone NOT NULL,
    purpose character varying(30) NOT NULL,
    recipient_uuid character varying(36) NOT NULL,
    requires_manual_review boolean DEFAULT false NOT NULL,
    shared_secret_version character varying(20),
    status character varying(20) NOT NULL,
    terminal_id character varying(100),
    CONSTRAINT terminal_commands_action_check CHECK (((action)::text = ANY ((ARRAY['PAYOUT'::character varying, 'REFUND'::character varying, 'WITHDRAW'::character varying])::text[]))),
    CONSTRAINT terminal_commands_purpose_check CHECK (((purpose)::text = ANY ((ARRAY['AUCTION_ESCROW'::character varying, 'LISTING_FEE_REFUND'::character varying, 'ADMIN_WITHDRAWAL'::character varying])::text[]))),
    CONSTRAINT terminal_commands_status_check CHECK (((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'IN_FLIGHT'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: terminal_commands_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terminal_commands ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terminal_commands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terminal_secrets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terminal_secrets (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    retired_at timestamp(6) with time zone,
    secret_value character varying(64) NOT NULL,
    version integer NOT NULL
);


--
-- Name: terminal_secrets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terminal_secrets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terminal_secrets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terminals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terminals (
    terminal_id character varying(100) NOT NULL,
    active boolean NOT NULL,
    http_in_url character varying(500) NOT NULL,
    last_heartbeat_at timestamp(6) with time zone,
    last_reported_balance bigint,
    last_seen_at timestamp(6) with time zone NOT NULL,
    region_name character varying(100),
    registered_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avg_buyer_rating numeric(3,2),
    avg_seller_rating numeric(3,2),
    banned_from_listing boolean DEFAULT false NOT NULL,
    bio text,
    cancelled_with_bids integer NOT NULL,
    completed_sales integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    dismissed_reports_count bigint DEFAULT 0 NOT NULL,
    display_name character varying(255),
    email character varying(255),
    email_verified boolean NOT NULL,
    escrow_expired_unfulfilled integer DEFAULT 0 NOT NULL,
    listing_suspension_until timestamp(6) with time zone,
    notify_email jsonb,
    notify_email_muted boolean NOT NULL,
    notify_sl_im jsonb,
    notify_sl_im_muted boolean NOT NULL,
    password_hash character varying(255) NOT NULL,
    penalty_balance_owed bigint DEFAULT 0 NOT NULL,
    profile_pic_url text,
    role character varying(10) DEFAULT 'USER'::character varying NOT NULL,
    sl_avatar_name character varying(255),
    sl_avatar_uuid uuid,
    sl_born_date date,
    sl_display_name character varying(255),
    sl_im_quiet_end time(0) without time zone,
    sl_im_quiet_start time(0) without time zone,
    sl_payinfo integer,
    sl_username character varying(255),
    token_version bigint DEFAULT 0 NOT NULL,
    total_buyer_reviews integer NOT NULL,
    total_seller_reviews integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    verified boolean NOT NULL,
    verified_at timestamp(6) with time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_codes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_codes (
    id bigint NOT NULL,
    auction_id bigint,
    code character varying(6) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    type character varying(20) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT verification_codes_type_check CHECK (((type)::text = ANY ((ARRAY['PLAYER'::character varying, 'PARCEL'::character varying])::text[])))
);


--
-- Name: verification_codes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: withdrawals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.withdrawals (
    id bigint NOT NULL,
    admin_user_id bigint NOT NULL,
    amount bigint NOT NULL,
    completed_at timestamp(6) with time zone,
    failure_reason character varying(500),
    notes character varying(1000),
    recipient_uuid character varying(36) NOT NULL,
    requested_at timestamp(6) with time zone NOT NULL,
    status character varying(16) NOT NULL,
    terminal_command_id bigint,
    CONSTRAINT withdrawals_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: withdrawals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.withdrawals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.withdrawals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_actions admin_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_actions
    ADD CONSTRAINT admin_actions_pkey PRIMARY KEY (id);


--
-- Name: auction_photos auction_photos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_photos
    ADD CONSTRAINT auction_photos_pkey PRIMARY KEY (id);


--
-- Name: auction_tags auction_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_tags
    ADD CONSTRAINT auction_tags_pkey PRIMARY KEY (auction_id, tag_id);


--
-- Name: auctions auctions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT auctions_pkey PRIMARY KEY (id);


--
-- Name: bans bans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bans
    ADD CONSTRAINT bans_pkey PRIMARY KEY (id);


--
-- Name: bids bids_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT bids_pkey PRIMARY KEY (id);


--
-- Name: bot_tasks bot_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_tasks
    ADD CONSTRAINT bot_tasks_pkey PRIMARY KEY (id);


--
-- Name: bot_workers bot_workers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_workers
    ADD CONSTRAINT bot_workers_pkey PRIMARY KEY (id);


--
-- Name: cancellation_logs cancellation_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cancellation_logs
    ADD CONSTRAINT cancellation_logs_pkey PRIMARY KEY (id);


--
-- Name: escrow_transactions escrow_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_transactions
    ADD CONSTRAINT escrow_transactions_pkey PRIMARY KEY (id);


--
-- Name: escrows escrows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrows
    ADD CONSTRAINT escrows_pkey PRIMARY KEY (id);


--
-- Name: fraud_flags fraud_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_flags
    ADD CONSTRAINT fraud_flags_pkey PRIMARY KEY (id);


--
-- Name: listing_fee_refunds listing_fee_refunds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_fee_refunds
    ADD CONSTRAINT listing_fee_refunds_pkey PRIMARY KEY (id);


--
-- Name: listing_reports listing_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_reports
    ADD CONSTRAINT listing_reports_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: parcel_tags parcel_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcel_tags
    ADD CONSTRAINT parcel_tags_pkey PRIMARY KEY (id);


--
-- Name: parcels parcels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels
    ADD CONSTRAINT parcels_pkey PRIMARY KEY (id);


--
-- Name: proxy_bids proxy_bids_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proxy_bids
    ADD CONSTRAINT proxy_bids_pkey PRIMARY KEY (id);


--
-- Name: reconciliation_runs reconciliation_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reconciliation_runs
    ADD CONSTRAINT reconciliation_runs_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: review_flags review_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_flags
    ADD CONSTRAINT review_flags_pkey PRIMARY KEY (id);


--
-- Name: review_responses review_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_responses
    ADD CONSTRAINT review_responses_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: saved_auctions saved_auctions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_auctions
    ADD CONSTRAINT saved_auctions_pkey PRIMARY KEY (id);


--
-- Name: sl_im_message sl_im_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sl_im_message
    ADD CONSTRAINT sl_im_message_pkey PRIMARY KEY (id);


--
-- Name: terminal_commands terminal_commands_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terminal_commands
    ADD CONSTRAINT terminal_commands_pkey PRIMARY KEY (id);


--
-- Name: terminal_secrets terminal_secrets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terminal_secrets
    ADD CONSTRAINT terminal_secrets_pkey PRIMARY KEY (id);


--
-- Name: terminals terminals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terminals
    ADD CONSTRAINT terminals_pkey PRIMARY KEY (terminal_id);


--
-- Name: users uk20su7vxoom3h0tcvqsi3plf3g; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk20su7vxoom3h0tcvqsi3plf3g UNIQUE (sl_avatar_uuid);


--
-- Name: parcel_tags uk2dsv6hayfefvs9i71xdixme14; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcel_tags
    ADD CONSTRAINT uk2dsv6hayfefvs9i71xdixme14 UNIQUE (code);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: parcels uk6j9htv37qwsi8tlcwicrq5rp7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels
    ADD CONSTRAINT uk6j9htv37qwsi8tlcwicrq5rp7 UNIQUE (sl_parcel_uuid);


--
-- Name: listing_reports uk_listing_reports_auction_reporter; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_reports
    ADD CONSTRAINT uk_listing_reports_auction_reporter UNIQUE (auction_id, reporter_id);


--
-- Name: saved_auctions uk_saved_auctions_user_auction; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_auctions
    ADD CONSTRAINT uk_saved_auctions_user_auction UNIQUE (user_id, auction_id);


--
-- Name: terminal_commands uk_tcmd_idempotency_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terminal_commands
    ADD CONSTRAINT uk_tcmd_idempotency_key UNIQUE (idempotency_key);


--
-- Name: review_responses ukm90an6qb6x5nwvk68l594m9ai; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_responses
    ADD CONSTRAINT ukm90an6qb6x5nwvk68l594m9ai UNIQUE (review_id);


--
-- Name: bot_workers uknwdegfu3xgusw7yx85dnv12oc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_workers
    ADD CONSTRAINT uknwdegfu3xgusw7yx85dnv12oc UNIQUE (sl_uuid);


--
-- Name: refresh_tokens uko2mlirhldriil2y7krapq4frt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uko2mlirhldriil2y7krapq4frt UNIQUE (token_hash);


--
-- Name: bot_workers uko3h30fkbqc38ww4grxoshuefp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_workers
    ADD CONSTRAINT uko3h30fkbqc38ww4grxoshuefp UNIQUE (name);


--
-- Name: escrows uko6q6l25btx4ylntrwpk5ffmdw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrows
    ADD CONSTRAINT uko6q6l25btx4ylntrwpk5ffmdw UNIQUE (auction_id);


--
-- Name: terminal_secrets ukrdmjybjcceae577xcmdb1va5x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terminal_secrets
    ADD CONSTRAINT ukrdmjybjcceae577xcmdb1va5x UNIQUE (version);


--
-- Name: review_flags uq_review_flags_review_flagger; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_flags
    ADD CONSTRAINT uq_review_flags_review_flagger UNIQUE (review_id, flagger_id);


--
-- Name: reviews uq_reviews_auction_reviewer; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT uq_reviews_auction_reviewer UNIQUE (auction_id, reviewer_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: verification_codes verification_codes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_codes
    ADD CONSTRAINT verification_codes_pkey PRIMARY KEY (id);


--
-- Name: withdrawals withdrawals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.withdrawals
    ADD CONSTRAINT withdrawals_pkey PRIMARY KEY (id);


--
-- Name: idx_admin_actions_admin_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_admin_actions_admin_user ON public.admin_actions USING btree (admin_user_id, created_at DESC);


--
-- Name: idx_admin_actions_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_admin_actions_target ON public.admin_actions USING btree (target_type, target_id, created_at DESC);


--
-- Name: idx_bans_ip_address; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bans_ip_address ON public.bans USING btree (ip_address);


--
-- Name: idx_bans_lifted_expires; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bans_lifted_expires ON public.bans USING btree (lifted_at, expires_at);


--
-- Name: idx_bans_sl_avatar_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bans_sl_avatar_uuid ON public.bans USING btree (sl_avatar_uuid);


--
-- Name: idx_listing_reports_auction; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_listing_reports_auction ON public.listing_reports USING btree (auction_id, updated_at DESC);


--
-- Name: idx_listing_reports_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_listing_reports_status ON public.listing_reports USING btree (status, auction_id);


--
-- Name: idx_refresh_tokens_user_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_tokens_user_active ON public.refresh_tokens USING btree (user_id, revoked_at);


--
-- Name: idx_reviews_auction; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reviews_auction ON public.reviews USING btree (auction_id);


--
-- Name: idx_reviews_reviewee_visible; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_reviews_reviewee_visible ON public.reviews USING btree (reviewee_id, reviewed_role, visible);


--
-- Name: ix_auction_tags_tag_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auction_tags_tag_id ON public.auction_tags USING btree (tag_id);


--
-- Name: ix_auctions_seller_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auctions_seller_status ON public.auctions USING btree (seller_id, status);


--
-- Name: ix_auctions_status_current_bid; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auctions_status_current_bid ON public.auctions USING btree (status, current_bid);


--
-- Name: ix_auctions_status_ends_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auctions_status_ends_at ON public.auctions USING btree (status, ends_at);


--
-- Name: ix_auctions_status_reserve; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auctions_status_reserve ON public.auctions USING btree (status, reserve_price);


--
-- Name: ix_auctions_status_starts_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_auctions_status_starts_at ON public.auctions USING btree (status, starts_at DESC);


--
-- Name: ix_bids_auction_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_bids_auction_created ON public.bids USING btree (auction_id, created_at);


--
-- Name: ix_bids_user_auction_amount; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_bids_user_auction_amount ON public.bids USING btree (user_id, auction_id, amount DESC);


--
-- Name: ix_bids_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_bids_user_created ON public.bids USING btree (user_id, created_at DESC);


--
-- Name: ix_escrow_tx_auction; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_escrow_tx_auction ON public.escrow_transactions USING btree (auction_id);


--
-- Name: ix_escrow_tx_escrow; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_escrow_tx_escrow ON public.escrow_transactions USING btree (escrow_id);


--
-- Name: ix_escrow_tx_sl_txn; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_escrow_tx_sl_txn ON public.escrow_transactions USING btree (sl_transaction_id);


--
-- Name: ix_escrows_payment_deadline; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_escrows_payment_deadline ON public.escrows USING btree (payment_deadline);


--
-- Name: ix_escrows_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_escrows_state ON public.escrows USING btree (state);


--
-- Name: ix_escrows_transfer_deadline; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_escrows_transfer_deadline ON public.escrows USING btree (transfer_deadline);


--
-- Name: ix_notification_user_unread_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notification_user_unread_created ON public.notification USING btree (user_id, read, created_at DESC);


--
-- Name: ix_notification_user_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_notification_user_updated ON public.notification USING btree (user_id, updated_at DESC);


--
-- Name: ix_parcels_area_sqm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_parcels_area_sqm ON public.parcels USING btree (area_sqm);


--
-- Name: ix_parcels_grid_coords; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_parcels_grid_coords ON public.parcels USING btree (grid_x, grid_y);


--
-- Name: ix_parcels_maturity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_parcels_maturity ON public.parcels USING btree (maturity_rating);


--
-- Name: ix_proxy_bids_auction_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_proxy_bids_auction_status ON public.proxy_bids USING btree (auction_id, status);


--
-- Name: ix_proxy_bids_user_auction; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_proxy_bids_user_auction ON public.proxy_bids USING btree (user_id, auction_id);


--
-- Name: ix_saved_auctions_user_saved_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_saved_auctions_user_saved_at ON public.saved_auctions USING btree (user_id, saved_at DESC);


--
-- Name: ix_sl_im_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sl_im_status_created ON public.sl_im_message USING btree (status, created_at);


--
-- Name: ix_sl_im_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sl_im_user_status ON public.sl_im_message USING btree (user_id, status);


--
-- Name: ix_tcmd_escrow; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_tcmd_escrow ON public.terminal_commands USING btree (escrow_id);


--
-- Name: ix_tcmd_listing_fee_refund; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_tcmd_listing_fee_refund ON public.terminal_commands USING btree (listing_fee_refund_id);


--
-- Name: ix_tcmd_status_next_attempt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_tcmd_status_next_attempt ON public.terminal_commands USING btree (status, next_attempt_at);


--
-- Name: ix_terminals_active_last_seen; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_terminals_active_last_seen ON public.terminals USING btree (active, last_seen_at);


--
-- Name: proxy_bids_one_active_per_user; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX proxy_bids_one_active_per_user ON public.proxy_bids USING btree (auction_id, user_id) WHERE ((status)::text = 'ACTIVE'::text);


--
-- Name: uq_auctions_parcel_locked_status; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_auctions_parcel_locked_status ON public.auctions USING btree (parcel_id) WHERE ((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ENDED'::character varying, 'ESCROW_PENDING'::character varying, 'ESCROW_FUNDED'::character varying, 'TRANSFER_PENDING'::character varying, 'DISPUTED'::character varying])::text[]));


--
-- Name: uq_notification_unread_coalesce; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_notification_unread_coalesce ON public.notification USING btree (user_id, coalesce_key) WHERE (read = false);


--
-- Name: uq_sl_im_pending_coalesce; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_sl_im_pending_coalesce ON public.sl_im_message USING btree (user_id, coalesce_key) WHERE ((status)::text = 'PENDING'::text);


--
-- Name: reviews fk1sjw2c8j34ew366vfqxergp0b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk1sjw2c8j34ew366vfqxergp0b FOREIGN KEY (reviewee_id) REFERENCES public.users(id);


--
-- Name: bans fk339gcujj338139hf1qd8llrfc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bans
    ADD CONSTRAINT fk339gcujj338139hf1qd8llrfc FOREIGN KEY (admin_user_id) REFERENCES public.users(id);


--
-- Name: fraud_flags fk3d5ijgesthcl10v3qak8kbjlv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_flags
    ADD CONSTRAINT fk3d5ijgesthcl10v3qak8kbjlv FOREIGN KEY (resolved_by_user_id) REFERENCES public.users(id);


--
-- Name: cancellation_logs fk3dsw9t16vrl8oa34ct9cprxhn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cancellation_logs
    ADD CONSTRAINT fk3dsw9t16vrl8oa34ct9cprxhn FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: fraud_flags fk3i2l0jfx144g8g65rapdxh7ym; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_flags
    ADD CONSTRAINT fk3i2l0jfx144g8g65rapdxh7ym FOREIGN KEY (parcel_id) REFERENCES public.parcels(id);


--
-- Name: escrow_transactions fk3iy8phlbrw5jyl0nigeiwhati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_transactions
    ADD CONSTRAINT fk3iy8phlbrw5jyl0nigeiwhati FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: listing_reports fk3vfn5w5g0yllxftti3ldjy45h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_reports
    ADD CONSTRAINT fk3vfn5w5g0yllxftti3ldjy45h FOREIGN KEY (reporter_id) REFERENCES public.users(id);


--
-- Name: saved_auctions fk4caqd9yc5pdyrs490u2nbwyw4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_auctions
    ADD CONSTRAINT fk4caqd9yc5pdyrs490u2nbwyw4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: escrow_transactions fk5q1xh1nnl5axk8ai6e3x8q979; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_transactions
    ADD CONSTRAINT fk5q1xh1nnl5axk8ai6e3x8q979 FOREIGN KEY (payee_id) REFERENCES public.users(id);


--
-- Name: listing_reports fk5q5gm076oxrl33cccpxvl82jl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_reports
    ADD CONSTRAINT fk5q5gm076oxrl33cccpxvl82jl FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: admin_actions fk75qyr4698jjoqah8d7j87jip5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_actions
    ADD CONSTRAINT fk75qyr4698jjoqah8d7j87jip5 FOREIGN KEY (admin_user_id) REFERENCES public.users(id);


--
-- Name: proxy_bids fk78wpa54e9dxsfwin6dmyc6cit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proxy_bids
    ADD CONSTRAINT fk78wpa54e9dxsfwin6dmyc6cit FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bot_tasks fk9xw9jtkg5ol4itos2e02u7v45; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_tasks
    ADD CONSTRAINT fk9xw9jtkg5ol4itos2e02u7v45 FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: auction_tags fka1ycp1yupd9pxp6rb08d7n47t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_tags
    ADD CONSTRAINT fka1ycp1yupd9pxp6rb08d7n47t FOREIGN KEY (tag_id) REFERENCES public.parcel_tags(id);


--
-- Name: bids fkbm89m2gow82dotpnlcp7t3p5f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT fkbm89m2gow82dotpnlcp7t3p5f FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: escrow_transactions fkd07w8ygrj0hkl3fhisd8yyywj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_transactions
    ADD CONSTRAINT fkd07w8ygrj0hkl3fhisd8yyywj FOREIGN KEY (payer_id) REFERENCES public.users(id);


--
-- Name: reviews fkd1isgfajhtdl8mgg29up6mofi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkd1isgfajhtdl8mgg29up6mofi FOREIGN KEY (reviewer_id) REFERENCES public.users(id);


--
-- Name: review_flags fkdo40jrivxns7k1egud7ijhkmy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_flags
    ADD CONSTRAINT fkdo40jrivxns7k1egud7ijhkmy FOREIGN KEY (flagger_id) REFERENCES public.users(id);


--
-- Name: fraud_flags fkebwjt3apo0k1m0p590003j3mi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fraud_flags
    ADD CONSTRAINT fkebwjt3apo0k1m0p590003j3mi FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: auctions fkecdwmck2lhpwbxtktix3hf82v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT fkecdwmck2lhpwbxtktix3hf82v FOREIGN KEY (listing_agent_id) REFERENCES public.users(id);


--
-- Name: review_responses fkgpf1f9hvtterlrnytx65nto9n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_responses
    ADD CONSTRAINT fkgpf1f9hvtterlrnytx65nto9n FOREIGN KEY (review_id) REFERENCES public.reviews(id);


--
-- Name: reviews fkgrkp5rp72clrsn87uq94uk6y5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkgrkp5rp72clrsn87uq94uk6y5 FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: review_flags fkgx0v9lnpr5pmtpiuj9v7mq3p5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_flags
    ADD CONSTRAINT fkgx0v9lnpr5pmtpiuj9v7mq3p5 FOREIGN KEY (review_id) REFERENCES public.reviews(id);


--
-- Name: listing_fee_refunds fki6tg2wr585sft5ch02ed1v69e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_fee_refunds
    ADD CONSTRAINT fki6tg2wr585sft5ch02ed1v69e FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: auction_tags fkk3kw4oid7kah7l8n1jiw7015w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_tags
    ADD CONSTRAINT fkk3kw4oid7kah7l8n1jiw7015w FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: saved_auctions fkktg8n4h2cdo65k133fvsmghgt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_auctions
    ADD CONSTRAINT fkktg8n4h2cdo65k133fvsmghgt FOREIGN KEY (auction_id) REFERENCES public.auctions(id) ON DELETE CASCADE;


--
-- Name: auctions fkld4p0ljlot0aetkmwn5lmntfw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT fkld4p0ljlot0aetkmwn5lmntfw FOREIGN KEY (parcel_id) REFERENCES public.parcels(id);


--
-- Name: bot_tasks fklpviupw3m4t2yybjj2u08r0mn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bot_tasks
    ADD CONSTRAINT fklpviupw3m4t2yybjj2u08r0mn FOREIGN KEY (escrow_id) REFERENCES public.escrows(id);


--
-- Name: auctions fklu950hyc1m3wi2km1mlrcttw1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT fklu950hyc1m3wi2km1mlrcttw1 FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: bids fkmb21nl8gr3srgnlch3s18oqv9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT fkmb21nl8gr3srgnlch3s18oqv9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: cancellation_logs fkne9lsrj1aqleolv365etx6cf8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cancellation_logs
    ADD CONSTRAINT fkne9lsrj1aqleolv365etx6cf8 FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: notification fknk4ftb5am9ubmkv1661h15ds9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fknk4ftb5am9ubmkv1661h15ds9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: auction_photos fkothbe2wuhh0f960a85fcnm0ef; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_photos
    ADD CONSTRAINT fkothbe2wuhh0f960a85fcnm0ef FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: proxy_bids fkqj8t0so94hrj0kioijebsorom; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proxy_bids
    ADD CONSTRAINT fkqj8t0so94hrj0kioijebsorom FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: bans fkqlyvdo30i2c8yjmr2pi12diya; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bans
    ADD CONSTRAINT fkqlyvdo30i2c8yjmr2pi12diya FOREIGN KEY (lifted_by_user_id) REFERENCES public.users(id);


--
-- Name: escrows fkra47hs1gbb3rg0plyepmrhxba; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrows
    ADD CONSTRAINT fkra47hs1gbb3rg0plyepmrhxba FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: listing_reports fkrg3eovb2fo4j9wef2w138g3w0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.listing_reports
    ADD CONSTRAINT fkrg3eovb2fo4j9wef2w138g3w0 FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: escrow_transactions fkruf60fseaely9t6dswgvvqejf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.escrow_transactions
    ADD CONSTRAINT fkruf60fseaely9t6dswgvvqejf FOREIGN KEY (escrow_id) REFERENCES public.escrows(id);


--
-- PostgreSQL database dump complete
--


