-- Escrow transfer split + Sell-To verification (spec 2026-05-17).
-- All columns nullable / default-0: no backfill (prod has no active listings).
ALTER TABLE escrows
    ADD COLUMN sell_to_confirmed_at            timestamptz,
    ADD COLUMN sell_to_last_result             varchar(32),
    ADD COLUMN sell_to_last_checked_at         timestamptz,
    ADD COLUMN sell_to_verify_attempts         integer     NOT NULL DEFAULT 0,
    ADD COLUMN buy_verify_seller_attempts      integer     NOT NULL DEFAULT 0,
    ADD COLUMN buy_verify_buyer_attempts       integer     NOT NULL DEFAULT 0,
    ADD COLUMN consecutive_sell_to_bot_failures integer    NOT NULL DEFAULT 0,
    ADD COLUMN next_owner_check_at             timestamptz,
    ADD COLUMN manual_verify_pending           boolean     NOT NULL DEFAULT false;

CREATE TABLE escrow_manual_reviews (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            uuid        NOT NULL UNIQUE,
    escrow_id            bigint      NOT NULL REFERENCES escrows(id),
    requested_by_user_id bigint      REFERENCES users(id),
    requested_role       varchar(16) NOT NULL,
    step                 varchar(16) NOT NULL,
    reason               varchar(32) NOT NULL,
    status               varchar(16) NOT NULL,
    resolved_by_admin_id bigint      REFERENCES users(id),
    resolution           varchar(32),
    admin_notes          text,
    resolved_at          timestamptz,
    created_at           timestamptz NOT NULL DEFAULT NOW(),
    updated_at           timestamptz NOT NULL DEFAULT NOW(),
    version              bigint      NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX uq_escrow_manual_review_open
    ON escrow_manual_reviews(escrow_id) WHERE status = 'OPEN';
CREATE INDEX idx_escrow_manual_review_status ON escrow_manual_reviews(status);
