spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/slpa
    username: slpa
    password: slpa
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          batch_size: 25
        order_inserts: true
        order_updates: true

cors:
  allowed-origin: http://localhost:3000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
