package com.slparcelauctions.backend.admin.audit;

public enum AdminActionType {
    DISMISS_REPORT,
    WARN_SELLER_FROM_REPORT,
    SUSPEND_LISTING_FROM_REPORT,
    CANCEL_LISTING_FROM_REPORT,
    CREATE_BAN,
    LIFT_BAN,
    PROMOTE_USER,
    DEMOTE_USER,
    RESET_FRIVOLOUS_COUNTER,
    REINSTATE_LISTING,
    DISPUTE_RESOLVED,
    LISTING_CANCELLED_VIA_DISPUTE,
    WITHDRAWAL_REQUESTED,
    OWNERSHIP_RECHECK_INVOKED,
    TERMINAL_SECRET_ROTATED,
    USER_DELETED_BY_ADMIN
}
